Avenzone/accounts/urls.py
from . import views
from django.urls import path, re_path
from django.conf.urls import url

app_name = 'accounts'

urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^explore/$', views.explore, name='explore'),
    url(r'^privacy/$', views.privacy, name='privacy'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^othersprofile/$', views.othersprofile, name='othersprofile'),
    url(r'^team/$', views.team, name='team'),
    url(r'^terms/$', views.terms, name='terms'),
    url(r'^verification/$', views.verification, name='verification'),
    url(r'^feedback/$', views.feedback, name='feedback'),
    url(r'^password/$', views.password, name='password'),
    url(r'^home/$', views.home, name='home'),
    url(r'^profile/$', views.profile, name='profile'),
    path('userprofile/<str:usern>/', views.friendprofile, name='friendprofile'),
    url(r'^notification/$', views.notification, name='notification'),
    url(r'^follow/$', views.follow, name='follow'),
    url(r'^followers/$', views.followers, name='followers'),
    url(r'^following/$', views.following, name='following'),
    url(r'^details/$', views.details, name='details'),
    url(r'^editdetails/$', views.editdetails, name='editdetails'),
    url(r'^createpost/$', views.createpost, name='createpost'),
    url(r'^rating/$', views.rating, name='rating'),


    re_path(r'^logoutbase/$', views.logoutbase, name='logoutbase'),
    re_path(r'^passwordbase/$', views.passwordbase, name='passwordbase'),
    re_path(r'^loginbase/$', views.loginbase, name='loginbase'),
    re_path(r'^registerbase/$', views.registerbase, name='registerbase'),
    re_path(r'^feedbackbase/$', views.feedbackbase, name='feedbackbase'),
]

Avenzone/accounts/templates/accounts/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Avenzone</title>

    <!--  CSS -->
    <link href="{% static "css/bootstrap/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/self/base.css" %}" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
        crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>


    <!-- BACKGROUND  -->
    <style>
      #home {
        background-image: url('{% static "images/background.png" %}');
        background-size: auto;
      }
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
  </head>

<body id="home">
  <header>
    <!-- NAVBAR AFTER LOGIN -->
    {% if user.is_authenticated %}
    <nav class="navbar navbar-expand-sm navbar-dark fixed-top dark">
          <div class="name space40">
            <a href="{% url 'accounts:index' %}"> <img src="{% static "images/AvenzonePerfect.png" %}" width="40" height="40" alt="" loading="lazy">Avenzone</a>
          </div>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarsExample03">

            <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
              <a class="textmuted" href="#" aria-label="Search">
                <svg xmlns="http://www.w3.org/2000/svg" width="1.75em" height="2em" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24" focusable="false"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"/><path d="M21 21l-5.2-5.2"/></svg>
              </a>
            </form>



            <li class="nav-item dropdown">
              <a class="textmuted" href="#" aria-label="Search" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <svg width="1.75em" height="2em" viewBox="0 0 16 16" class="bi bi-caret-down-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path d="M7.247 11.14L2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1 1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z"/>
                </svg>
              </a>

              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="{% url 'accounts:verification' %}">Verification</a>
                <a class="dropdown-item" href="{% url 'accounts:password' %}">Password</a>
                <a class="dropdown-item" href="{% url 'accounts:feedback' %}">Feedback</a>
                <a class="dropdown-item" href="{% url 'accounts:logoutbase' %}">Log Out</a>

              </div>

            </li>
         </div>

        <div class="space40">
          <a class="textmuted" href="{% url 'accounts:profile' %}" aria-label="Search">
            <svg width="1.75em" height="2em" viewBox="0 0 16 16" class="bi bi-person-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path d="M13.468 12.37C12.758 11.226 11.195 10 8 10s-4.757 1.225-5.468 2.37A6.987 6.987 0 0 0 8 15a6.987 6.987 0 0 0 5.468-2.63z"/>
            <path fill-rule="evenodd" d="M8 9a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
            <path fill-rule="evenodd" d="M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zM0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8z"/>
            </svg>
          </a>
        </div>

        <div class="space40">
          <a class="textmuted" href="{% url 'accounts:explore' %}" aria-label="Search">
            <svg width="1.75em" height="2em" viewBox="0 0 16 16" class="bi bi-plus-square-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm6.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3v-3z"/>
          </svg>
          </a>
        </div>

        <div class="space40">
          <a class="textmuted" href="{% url 'accounts:notification' %}" aria-label="Search">
            <svg width="1.75em" height="2em" viewBox="0 0 16 16" class="bi bi-bell-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zm.995-14.901a1 1 0 1 0-1.99 0A5.002 5.002 0 0 0 3 6c0 1.098-.5 6-2 7h14c-1.5-1-2-5.902-2-7 0-2.42-1.72-4.44-4.005-4.901z"/>
            </svg>
          </a>
        </div>

        <div class="space40">
          <a class="textmuted" href="{% url 'accounts:home' %}" aria-label="Search">
            <svg width="1.75em" height="2em" viewBox="0 0 16 16" class="bi bi-house-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M8 3.293l6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6zm5-.793V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
            <path fill-rule="evenodd" d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z"/>
            </svg>
          </a>
        </div>

        <button type="submit" class="btn btn-danger btn-sm"><a class="textmuted" href="{% url 'accounts:createpost' %}">Create post</a></button>
    </nav>

    {% else %}
    <!-- NAVBAR BEFORE LOGIN -->

      <nav class="navbar navbar-expand-sm navbar-dark dark">
        <div class="name">
          <a href="{% url 'accounts:index' %}"> <img src="{% static "images/AvenzonePerfect.png" %}" width="40" height="40" alt="" loading="lazy">Avenzone</a>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample03">
          <ul class="navbar-nav mr-auto">
          	<li class="nav-item active">
               <div class="register">
                  <a  href="{% url 'accounts:index' %}">Home <span class="sr-only">(current)</span></a>
                <div>
            </li>
            <li class="nav-item ">
               <div class="register">
                  <a  href="{% url 'accounts:team' %}">Contact </span></a>
                <div>
            </li>
            <li class="nav-item ">
               <div class="register">
                  <a  href="{% url 'accounts:signup' %}">Sign Up </span></a>
                <div>
            </li>
          </ul>
        </div>
      </nav>

      {% endif %}

  </header>

{% block body_block %}


  {% endblock %}

  <!-- FOOTER -->

                  <footer>
                    <div class="container">
                        <div class="row">

                          <div class="col-md-4">
                              <div class="more-info">
                                  <ul>
                                      <li><img class="mb-2" src="{% static "images/AvenzonePerfect.png" %}" alt="" width="24" height="24"><span>Avenzone</span></li>
                                      <li> Social Gaming Platform</li>
                                      <li><a href="http://www.mnnit.ac.in/">MNNIT Allahabad</a></li>
                                  </ul>
                              </div>
                          </div>

                          <div class="col-md-4">
                              <div class="more-info">
                                  <ul>
                                    <li><span> More From Us </span></li>
                                    <li><a  href="{% url 'accounts:about' %}">About</a></li>
                                    <li><a href="{% url 'accounts:team' %}">Team</a></li>
                                    <li><a href="#">Cool stuff</a></li>
                                  </ul>
                              </div>
                          </div>

                          <div class="col-md-4">
                            <div class="more-info">
                                <ul>
                                    <li><span>Legal Stuff </span></li>
                                    <li><a href="{% url 'accounts:privacy' %}">Privacy</a></li>
                                    <li><a href="{% url 'accounts:terms' %}">Terms</a></li>
                                    <li><a href="#">Locations</a></li>
                                </ul>
                            </div>
                          </div>
                        </div>

 <!-- BOTTOM FOOTER -->
                        <div class="bottom-footer">
                            <p><span >Copyright © 2020 Avenzone</span></p>
                        </div>
                    </footer>

   <!--JS FILES  -->

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="{% static "js/jquery.slim.min.js" %}"><\/script>')</script>
<script  src="{% static "js/jquery-2.1.1.min.js" %}"></script>
<script  src="{% static "js/bootstrap.min.js" %}"></script>
<script src="{% static "js/bootstrap.bundle.min.js" %}"></script>

</body>
</html>

Avenzone/accounts/templates/accounts/details.html
<!doctype html>
{% extends "accounts/base.html" %}
{% block body_block %}
{% load static %}

    <link href="{% static "css/self/details.css" %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

        @media screen and (min-width: 601px) {
  div.examplet {
    font-size: 80px;
  }
}

@media screen and (max-width: 600px) {
  div.examplet {
    font-size: 30px;
  }
}
    </style>

    <main role="main" class="container" style="margin-top: 65px;">

    <!-- first container   -->

       <div class="dark2">
         <img src="{% static "images/gamer.jpg" %}"  alt="" loading="lazy" id="over" style="" class="responsive">
         <div class="container responsive" >
             <span href="" class="header2 username responsive examplet"><img src="/media/{{profile.profile_pic}}" width="80px" height="80px" style="border-radius:170px; ">
             {{user}} <button type="button" class="btn btn-danger"><a class="textmuted" href ="{% url 'accounts:editdetails' %}">Edit Profile</a></button></span>
         </div>
       </div>

       <!-- intro block -->
<div class="row" style="background: rgba(85, 85, 85, 0.3);">

           <aside class="col-md-4 blog-sidebar">
             <div class="p-4 mb-3 rounded" style="background: rgba(00, 00, 00, 0.3); margin: 30px 0px 0px 0px;">
               <h1 class="h1" style="color: gray">INTRO</h1>

               <div class="row space30" >
                  <h3 class="font-italic intro"> <img src="{% static "images/gstar.png" %}" width="45px"><a href="#">Rating</a></h3>
               </div>
               <div class="row space30" >
                  <h3 class="font-italic intro"> <img src="{% static "images/book.png" %}" width="45px"><a href="{% url 'accounts:details' %}"> About</a></h3>
               </div>
               <div class="row space30" >
                  <h3 class="font-italic intro"> <img src="{% static "images/trophies.png" %}" width="45px"><a href="{% url 'accounts:followers' %}"> Followers</a></h3>
               </div>
               <div class="row space30" >
                  <h3 class="font-italic intro"> <img src="{% static "images/emoji.png" %}" width="45px"> <a href="{% url 'accounts:following' %}"> Following</a></h3>
               </div>
              </div>
          </aside>
   <!-- intro block ends here -->

<!-- post block -->
<div class="col-md-8 blog-main">
  <div class="blog-post" style="padding: 2px; background: rgba(00,00,00,0.3);">
     <h2 class="blog-post-title" style="color: gray; background: rgba(00,00,00,0.3);" >ABOUT</h2>

       <ul style="color: grey">

          <li style="font-size: 20px">Bio
               <ul>
                <li> {{profile.bio}} </li>
              </ul>
           </li>

           <li style="font-size: 20px">Personal info
            <ul>
                 <li>City : {{profile.city}}</li>
                 <li>Country : {{profile.country}}</li>
                 <li>Gender : {{profile.gender}}</li>
                 <li>Date of Birth : {{profile.dob}}</li>
            </ul>
           </li>

           <li style="font-size: 20px">Contact info
               <ul>
                 <!-- <li>Facebook link : </li> -->
                 <li>Email address : {{user.email}}</li>
                 <li>Phone no.: {{profile.phone}}</li>
               </ul>
           </li>
        </ul>
    </div>
  </div>
</div>
      <div class = "space50"></div>

<!-- post block ends -->
</main>
{% endblock %}

Avenzone/accounts/templates/accounts/followers.html
<!doctype html>
{% extends "accounts/base.html" %}
{% block body_block %}
{% load static %}

    <link href="{% static "css/self/follow.css" %}" rel="stylesheet"><!doctype html>

<main role="main" class="container">
  <div  class="header2">
    <img class="mr-3" >
    <div class="lh-100">
    </div>
  </div>


  <!-- following -->
  <div class="my-3 p-3 rounded shadow-sm" style="background: rgba(85, 85, 85, 0.3)">
    <h5 class="border-bottom border-gray pb-2 mb-0"  style="color: #545454">Followers</h5>

    <!-- <div class="media text-muted pt-3">
      <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title>
         <image width="50" height="40" xlink:href="../assets/brand/lady.png" clip-path="url(#myCircle)" /></svg>
      <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <div class="d-flex justify-content-between align-items-center w-100">
          <strong class="text-gray-dark">Full Name</strong>
          <a href="#">Following</a>
        </div>
        <span class="d-block">@username</span>
      </div>
    </div> -->
    {% for follower in followers %}
    <div class="media text-muted pt-3">
      <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><image width="50" height="40" xlink:href="/media/{{follower.followed_by.profile_pic}}" clip-path="url(#myCircle)" /></svg>
      <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <div class="d-flex justify-content-between align-items-center w-100">
          <strong class="text-gray-dark"><a href="{% url 'accounts:friendprofile' follower.followed_by.auth_user %}"> {{follower.followed_by.auth_user.first_name}} {{follower.followed_by.auth_user.last_name}} </a></strong>
          <a href="#">Following</a>
        </div>
        <span class="d-block">@{{follower.followed_by.auth_user}}</span>
      </div>
    </div>
    {% endfor %}

    <!-- <div class="media text-muted pt-3">
      <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><image width="50" height="40" xlink:href="../assets/brand/lady.png" clip-path="url(#myCircle)" />
      <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <div class="d-flex justify-content-between align-items-center w-100">
          <strong class="text-gray-dark">Full Name</strong>
          <a href="#">Following</a>
        </div>
        <span class="d-block">@username</span>
      </div>
    </div>

    <div class="media text-muted pt-3">
      <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><image width="50" height="40" xlink:href="../assets/brand/lady.png" clip-path="url(#myCircle)" /></svg>
      <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <div class="d-flex justify-content-between align-items-center w-100">
          <strong class="text-gray-dark">Full Name</strong>
          <a href="#">Following</a>
        </div>
        <span class="d-block">@username</span>
      </div>
    </div>

    <div class="media text-muted pt-3">
      <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><image width="50" height="40" xlink:href="../assets/brand/lady.png" clip-path="url(#myCircle)" />
      <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <div class="d-flex justify-content-between align-items-center w-100">
          <strong class="text-gray-dark">Full Name</strong>
          <a href="#">Following</a>
        </div>
        <span class="d-block">@username</span>
      </div>
    </div>

    <div class="media text-muted pt-3">
      <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><image width="50" height="40" xlink:href="../assets/brand/lady.png" clip-path="url(#myCircle)" /></svg>
      <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <div class="d-flex justify-content-between align-items-center w-100">
          <strong class="text-gray-dark">Full Name</strong>
          <a href="#">Following</a>
        </div>
        <span class="d-block">@username</span>
      </div>
    </div>

    <div class="media text-muted pt-3">
      <svg class="bd-placeholder-img mr-2 rounded" width="32" height="32" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><image width="50" height="40" xlink:href="../assets/brand/lady.png" clip-path="url(#myCircle)" />
      <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <div class="d-flex justify-content-between align-items-center w-100">
          <strong class="text-gray-dark">Full Name</strong>
          <a href="#">Following</a>
        </div>
        <span class="d-block">@username</span>
      </div>
    </div> -->

    <small class="d-block text-right mt-3">
      <a href="#">All following</a>
    </small>

  </div>
  <!-- end of following -->

</main>
    <script src="offcanvas.js"></script></body>
    {% endblock %}

Avenzone/accounts/templates/accounts/password.html
<!doctype html>
{% extends "accounts/base.html" %}
{% block body_block %}
{% load static %}

    <link href="{% static "css/self/password.css" %}" rel="stylesheet">
    <main role="main">
      <section class="jumbotron text-center">
        <div class="container">
          <h1>Don't Worry !! Continue Your Amazing Experience , Find a Tricky one this time !!</h1>
        </div>
      </section>
    </main>


      <div class="space50"></div>

  <div class="container">
    <div class="col-md-8 order-md-1">

      <form class="needs-validation" method="POST" action="{% url 'accounts:passwordbase' %}" novalidate> {% csrf_token %}

        <div class="mb-3">
          <label for="email">Email <span class="text-muted"></span></label>
          <input type="email" class="form-control" id="email" placeholder="you@example.com">
          <div class="invalid-feedback">
            Please enter a valid email address for shipping updates.
          </div>
        </div>

        <div class="mb-3">
          <label for="address">Password</label>
          <input type="password" class="form-control" name="address" id="address" placeholder="Enter Your Password" required>
          <div class="invalid-feedback">
            Please enter a valid password
          </div>
        </div>

        <div class="mb-3">
          <label for="address">Confirm Password</label>
          <input type="password" class="form-control" id="address" placeholder="Confirm Your Password" required>
          <div class="invalid-feedback">
            Password mismatched
          </div>
        </div>

          <hr class="mb-4">
          <div class="custom-control custom-checkbox">
            <input type="checkbox" class="custom-control-input" id="same-address">
            <label class="custom-control-label" for="same-address">I agree to privacy terms and policy.</label>
          </div>

        <hr class="mb-4">
        <!-- Button trigger modal -->
        <button type="submit" class="btn btn-danger" data-toggle="modal" data-target="#staticBackdrop">
         Change Password
       </button>

       <div class="modal f" id="staticBackdrop"  tabindex="-1"  aria-hidden="true">
         <div class="modal-dialog">
           <div class="modal-content">
             <div class="modal-header">
               <h5 class="modal-title">Change Passowrd</h5>
               <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                 <span aria-hidden="true">&times;</span>
               </button>
             </div>
             <div class="modal-body">
              Your Password is changed !!
             </div>
             <div class="modal-footer">
               <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>

             </div>
           </div>
         </div>
       </div>

      </div>
    </form>
  </div>
</div>

 <div class="space50"></div>
 <script src="{% static "js/form-validation.js" %}"></script></body>
{% endblock %}